// DO NOT EDIT!
// Automatically generated by xcdl for 'micro-os-plus.diag.trace'. (TODO)

// ----------------------------------------------------------------------------

#ifndef MICRO_OS_PLUS_DIAG_TRACE_DEFINES_H_
#define MICRO_OS_PLUS_DIAG_TRACE_DEFINES_H_

// ----------------------------------------------------------------------------

#if defined(MICRO_OS_PLUS_TRACE)

// The portable trace::printf() code.
#if !defined(MICRO_OS_PLUS_DIAG_TRACE_ENABLED)
#define MICRO_OS_PLUS_DIAG_TRACE_ENABLED
#endif // MICRO_OS_PLUS_DIAG_TRACE_ENABLED

// The size in bytes of the stack buffer used by vsnprintf() to store the
// diagnostics line.
#if !defined(MICRO_OS_PLUS_DIAG_TRACE_PRINTF_BUFFER_ARRAY_SIZE_INTEGER)
#define MICRO_OS_PLUS_DIAG_TRACE_PRINTF_BUFFER_ARRAY_SIZE_INTEGER (512)
#endif // MICRO_OS_PLUS_DIAG_TRACE_PRINTF_BUFFER_ARRAY_SIZE_INTEGER

#endif // defined(MICRO_OS_PLUS_TRACE)

// ----------------------------------------------------------------------------

#endif // MICRO_OS_PLUS_DIAG_TRACE_DEFINES_H_

// ----------------------------------------------------------------------------
