// DO NOT EDIT!
// Automatically generated by xcdl for 'micro-os-plus.utils.lists'. (TODO)

#ifndef MICRO_OS_PLUS_UTILS_LISTS_DEFINES_H_
#define MICRO_OS_PLUS_UTILS_LISTS_DEFINES_H_

// Display trace messages in lists when TRACE is enabled.
#if !defined(MICRO_OS_PLUS_UTILS_LISTS_TRACE_ENABLED)
// #define MICRO_OS_PLUS_UTILS_LISTS_TRACE_ENABLED
#endif //

// Display trace messages in lists constructors and descriptors when TRACE is
// enabled.
#if !defined(MICRO_OS_PLUS_UTILS_LISTS_TRACE_CONSTRUCTORS_ENABLED)
// #define MICRO_OS_PLUS_UTILS_LISTS_TRACE_CONSTRUCTORS_ENABLED
#endif // MICRO_OS_PLUS_UTILS_LISTS_TRACE_CONSTRUCTORS_ENABLED

#endif // MICRO_OS_PLUS_UTILS_LISTS_DEFINES_H_
