// DO NOT EDIT!
// Automatically generated by xcdl. (TODO)

// ----------------------------------------------------------------------------

#ifndef MICRO_OS_PLUS_DIAG_TRACE_DEFINES_H_
#define MICRO_OS_PLUS_DIAG_TRACE_DEFINES_H_

// ----------------------------------------------------------------------------

// Hack used until xcdl will generate different files for debug configurations.
// For now tie the diag trace to the debug configuration.
#if defined(MICRO_OS_PLUS_DEBUG_ENABLED)
// The portable trace::printf() code.
#if !defined(MICRO_OS_PLUS_DIAG_TRACE_ENABLED)
#define MICRO_OS_PLUS_DIAG_TRACE_ENABLED
#endif // !defined(MICRO_OS_PLUS_DIAG_TRACE_ENABLED)
#endif // defined(MICRO_OS_PLUS_DEBUG_ENABLED)

// The size in bytes of the stack buffer used by vsnprintf() to store the
// diagnostics line.
#if !defined(MICRO_OS_PLUS_DIAG_TRACE_PRINTF_BUFFER_ARRAY_SIZE_INTEGER)
#define MICRO_OS_PLUS_DIAG_TRACE_PRINTF_BUFFER_ARRAY_SIZE_INTEGER (512)
#endif // !defined(MICRO_OS_PLUS_DIAG_TRACE_PRINTF_BUFFER_ARRAY_SIZE_INTEGER)

// The synthetic POSIX architecture is an environment that allows to run µOS++
// applications on a POSIX host, using the POSIX API.
#if !defined(MICRO_OS_PLUS_DIAG_TRACE_POSIX_ENABLED)
#define MICRO_OS_PLUS_DIAG_TRACE_POSIX_ENABLED
#endif // !defined(MICRO_OS_PLUS_DIAG_TRACE_POSIX_ENABLED)

// The diag trace channel is implemented over the POSIX standard output.
#if !defined(MICRO_OS_PLUS_DIAG_TRACE_POSIX_STDOUT_ENABLED)
#define MICRO_OS_PLUS_DIAG_TRACE_POSIX_STDOUT_ENABLED
#endif // !defined(MICRO_OS_PLUS_DIAG_TRACE_POSIX_STDOUT_ENABLED)

// ----------------------------------------------------------------------------

#endif // MICRO_OS_PLUS_DIAG_TRACE_DEFINES_H_

// ----------------------------------------------------------------------------
