// DO NOT EDIT!
// Automatically generated by xcdl. (TODO)

// ----------------------------------------------------------------------------

#ifndef MICRO_OS_PLUS_DEVICE_DEFINES_H_
#define MICRO_OS_PLUS_DEVICE_DEFINES_H_

// ----------------------------------------------------------------------------

#if !defined(MICRO_OS_PLUS_DEVICE_QEMU_CORTEX_M7)
#define MICRO_OS_PLUS_DEVICE_QEMU_CORTEX_M7
#endif // !defined(MICRO_OS_PLUS_DEVICE_QEMU_CORTEX_M7)

// ----------------------------------------------------------------------------

#endif // MICRO_OS_PLUS_DEVICE_DEFINES_H_

// ----------------------------------------------------------------------------
